version: '3.8'

services:

  flower:
    image: mher/flower
    ports:
      - 5555:5555
    environment:
     - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      # Expose the port for the worker to add/get tasks
      - 5673:5672
      # OPTIONAL: Expose the GUI port
      # - 15672:15672

  redis:
    container_name: redis
    image: redis:7.0.11-alpine

  django:
    container_name: django
    build:
      context: ./dcelery
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./dcelery:/usr/src/app/
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=0930jd30j9jd09j09j109fj01j9f
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis
  
  celery:
    container_name: celery
    build:
      context: ./dcelery
    # command: celery -A dcelery worker -l INFO -Q celery,celery:1,celery:2,celery:3
    command: celery -A dcelery worker -l INFO -Q tasks,dead_letter -E -B
    volumes:
      - ./dcelery:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=0930jd30j9jd09j09j109fj01j9f
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis
      - django
      - rabbitmq

  celery2:
    container_name: celery2
    build:
      context: ./celeryworker
      dockerfile: Dockerfile
    command: celery -A celerytask worker --loglevel=INFO -B
    volumes:
      - ./celeryworker:/usr/src/app/
    depends_on:
      - redis
      - django